swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints for the phase transactions
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v2
schemes:
  - http
paths:
  /user/account:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Account API
      description: API for fetching an user account's data
      parameters:
        - type: string
          in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: User account's data retrieved successully
          schema:
            $ref: "#/definitions/AccountResponse"
        "400":
          description: Invalid Token
        "500":
          description: Internal Server Error

  /user/transactions:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Transactions API
      description: API for fetching an user account's transactions data
      parameters:
        - type: string
          in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Fetch transactions data by using account id
          required: true
          schema:
            $ref: "#/definitions/Transactions"
      produces:
        - application/json
      responses:
        "200":
          description: User transactions data retrieved successully
          schema:
            $ref: "#/definitions/TransactionsResponse"
        "400":
          description: Invalid token or account Id
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Transactions API
      description: API for updating an user account's transactions data
      parameters:
        - type: string
          in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update transactions data by using transaction id
          required: true
          schema:
            $ref: "#/definitions/TransactionsUpdate"
      produces:
        - application/json
      responses:
        "200":
          description: User transactions data have been updated successully
          schema:
            $ref: "#/definitions/TransactionsResponse"
        "400":
          description: Invalid token or transaction id
        "500":
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:
  AccountResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          accountData:
            type: array
            items:
              type: object
              properties:
                title:
                  type: string
                amount:
                  type: string
                description:
                  type: string
                accountId:
                  type: string
  Transactions:
    type: object
    properties:
      accountId:
        type: string

  TransactionsResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          accountId:
            type: string
          transactions:
            type: array
            items:
              type: object
              properties:
                createdAt:
                  type: string
                description:
                  type: string
                amount:
                  type: string
                balance:
                  type: string
                type:
                  type: string
                category:
                  type: string
                notes:
                  type: string
                transactionId:
                  type: string
                updatedAt:
                  type: string

  TransactionsUpdate:
    type: object
    properties:
      transactionId:
        type: string
      category:
        type: string
      notes:
        type: string
