swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: This document contains all available API endpoints for the phase transactions about the ARGENTBANK server
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v2
schemes:
  - http
paths:
  /user/account:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Get all data account of an user
      description: Return an object containing an array with account's data objects
      parameters:
        - type: string
          in: header
          name: Authorization
          description: Attach Bearer JWT token for authorization
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: User account's data retrieved successully
          schema:
            $ref: "#/definitions/AccountResponse"
        "401":
          description: Invalid token, authorisation refused
        "404":
          description: Resource not found
        "500":
          description: Internal Server Error

  /user/transactions/:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Get all transactions of an user's account
      description: Return an object containing an array with all transactions data objects
      operationId: getAllTransactions
      parameters:
        - type: string
          in: header
          name: Authorization
          description: Attach Bearer JWT token for authorization
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: User transactions data retrieved successully
          schema:
            $ref: "#/definitions/TransactionsResponse"
        "401":
          description: Invalid token, authorisation refused
        "404":
          description: Resource not found
        "500":
          description: Internal Server Error

  /user/transactions/findByAccountId:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Find transactions for an user account's category by using account Id
      description: Return an object containing an array with all transactions data objects filtered
      operationId: findTransactionsByAccountId
      parameters:
        - type: string
          in: header
          name: Authorization
          description: Attach Bearer JWT token for authorization
          required: true
        - type: string
          name: accountId
          in: query
          description: accountId value that need to be considered for transactions filtering
          required: true
          default: checking
          enum:
            - checking
            - savings
            - credit-card
      produces:
        - application/json
      responses:
        "200":
          description: User transactions data retrieved successully
          schema:
            $ref: "#/definitions/TransactionsResponse"
        "400":
          description: Invalid fields
        "401":
          description: Invalid token, authorisation refused
        "404":
          description: Resource not found
        "500":
          description: Internal Server Error

  /user/transactions/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Find a transaction by his id
      description: Return an object containing a single transaction object
      parameters:
        - type: string
          in: header
          name: Authorization
          description: Attach Bearer JWT token for authorization
          required: true
        - type: integer
          in: path
          name: transactionId
          description: Id of the transaction researched
          required: true
          format: int64
      produces:
        - application/json
      responses:
        "200":
          description: User transaction data retrieved successfully
          schema:
            $ref: "#/definitions/TransactionResponse"
        "400":
          description: Invalid transaction id
        "401":
          description: Invalid token, authorisation refused
        "404":
          description: Resource not found
        "500":
          description: Internal Server Error
    patch:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Update specific data from a transaction by his id
      description: Return an object containing single transaction with content updated
      parameters:
        - type: string
          in: header
          name: Authorization
          description: Attach Bearer JWT token for authorization
          required: true
        - type: integer
          in: path
          name: transactionId
          description: Id of the transaction containing data to update
          required: true
          format: int64
        - type: string
          name: category
          in: query
          description: Content to update for transaction's data category
        - type: string
          name: notes
          in: query
          description: Content to update for transaction's data notes

      produces:
        - application/json
      responses:
        "200":
          description: User transaction data have been updated successully
          schema:
            $ref: "#/definitions/TransactionUpdatedResponse"
        "400":
          description: Invalid transaction id or fields
        "401":
          description: Invalid token, authorisation refused
        "404":
          description: Resource not found
        "500":
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:
  AccountResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          accountData:
            type: array
            items:
              type: object
              properties:
                title:
                  type: string
                amount:
                  type: string
                description:
                  type: string
                accountId:
                  type: string
  Transactions:
    type: object
    properties:
      accountId:
        type: string

  TransactionsResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          transactions:
            type: array
            items:
              type: object
              properties:
                createdAt:
                  type: string
                description:
                  type: string
                amount:
                  type: string
                balance:
                  type: string
                type:
                  type: string
                category:
                  type: string
                notes:
                  type: string
                transactionId:
                  type: string
                updatedAt:
                  type: string
                accountId:
                  type: string

  TransactionResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          transactions:
            type: object
            properties:
              createdAt:
                type: string
              description:
                type: string
              amount:
                type: string
              balance:
                type: string
              type:
                type: string
              category:
                type: string
              notes:
                type: string
              transactionId:
                type: string
              updatedAt:
                type: string
              accountId:
                type: string

  TransactionUpdatedResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          transactions:
            type: object
            properties:
              category:
                type: string
              notes:
                type: string
              transactionId:
                type: string
              updatedAt:
                type: string
